// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq7Xc-bmHxfHcL1RAumsUeaqeL20jqcTI',
    appId: '1:683528231911:web:b800d04e8cfa998334fb42',
    messagingSenderId: '683528231911',
    projectId: 'leble-app',
    authDomain: 'leble-app.firebaseapp.com',
    storageBucket: 'leble-app.appspot.com',
    measurementId: 'G-8ZY1697DE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHc0GmfzPFEMhjTJo6XA9P2hWYV4qbrw',
    appId: '1:683528231911:android:9b99d86fbfbeff6b34fb42',
    messagingSenderId: '683528231911',
    projectId: 'leble-app',
    storageBucket: 'leble-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQ3Zpdt7jjVeADS31XffHNMlnsZtOxog',
    appId: '1:683528231911:ios:6cbe7bd061e28e9834fb42',
    messagingSenderId: '683528231911',
    projectId: 'leble-app',
    storageBucket: 'leble-app.appspot.com',
    iosBundleId: 'com.example.lebleTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQ3Zpdt7jjVeADS31XffHNMlnsZtOxog',
    appId: '1:683528231911:ios:ceed6e09136401e834fb42',
    messagingSenderId: '683528231911',
    projectId: 'leble-app',
    storageBucket: 'leble-app.appspot.com',
    iosBundleId: 'com.example.lebleTest1.RunnerTests',
  );
}
